spring:
  cloud:
    gateway:
      routes:
        - id: sebsabi-core-service
          uri: lb://sebsabi-core-service
          predicates:
            - Path=/api/core/**
          filters:
            - AuthenticationFilter

        - id: sebsabi-core-documentation
          uri: lb://sebsabi-core-service
          predicates:
            - Path=/sebsabi-documentation.html


        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web/**
          filters:
            - SetPath=/

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: api-gateway
      i

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
